spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            Path=/customers/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            Path=/products/**