spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id : customer-service
              uri: http://localhost:8000
              predicates:
                - path=/customers/**
            - id : inventory-service
              uri: http://localhost:8001
              predicates:
                - path=/products/**